### ISSUE TITLE
iLive only showing up to 64 inputs

### ISSUE THREAD

**Issue by LBCProduction** [bitfocus/companion-module-allenheath-dlive-ilive#10]
We have 128 inputs on our ilive system.  This plugin works to mute/unmute/etc for inputs up to 64, but there doesn't seem to be a way to modify inputs 65-128.  Is there a way to do this?

**Comment by MeestorX** [comment]
Please contact me at discourse.checkcheckonetwo.com and I'll see what can be done to rectify this.
