### ISSUE TITLE
Using dlive module to connect to a Qu-32

### ISSUE THREAD

**Issue by crisgaret** [bitfocus/companion-module-allenheath-dlive-ilive#3]
Hoping this is the correct place to ask this. I'm trying to connect companion to my QU-32 and after I enter the IP, logs shows 'MIDI Connected' then I get the following TCP error:

 instance(dLive): TCP error: connect ECONNREFUSED 192.168.78.121:51321

I'm guessing this is a setup problem on my end, but just looking for some direction or help. Thanks.

**Comment by MeestorX** [comment]
dLive module is for the dLive consoles, not the Qu.

**Comment by crisgaret** [comment]
Yeah, I was afraid of that. Digging through here I found a note in the module requests ([#91](https://github.com/bitfocus/companion-module-requests/issues/91)) that mentioned the dlive module, and I think I just misunderstood, that it might work for the Qu. 

I'll poke around in the module requests. Thanks for getting back to me.

**Comment by MeestorX** [comment]
My understanding is that the Qu MIDI protocol is not the same as the dLive.

If you wouldn't mind, please close this issue when you get a chance.
