### ISSUE TITLE
Setting the fader volume doesn't work on QU-16

### ISSUE THREAD

**Issue by LoganSulpizio** [bitfocus/companion-module-allenheath-dlive-ilive#7]
On a Qu-16, I could easily mute and unmute a channel or an aux. But when I'm trying to set the volume fader of any input or an aux, it doesn't work.

Also, it would be great to have a option to increase/decrease the volume from 1 dB, instead of having to choose at which level you have to set it up.

**Comment by maxks** [comment]
In this module will be remove any referring to QU16 because will be build a specific module for all QU models.
Architecture of iLive is similar but not the same of the QU so it's preferable separate it.

**Comment by LoganSulpizio** [comment]
> In this module will be remove any referring to QU16 because will be build a specific module for all QU models.

Ok, thank you for your answer. Do you already know when the QU module will be available?

Meanwhile, is there a way to trigger the sending of TCP packets with companion? This would enable us to "build" some commands ourselves. Allen&Heath explains how to do so [here](http://support.allen-heath.com/Knowledgebase/Article/View/using-stream-deck-with-dlive), but it is with the native app of Elgato stream deck. Is there a way to do the same with Bitfocus Companion?

**Comment by maxks** [comment]
Now I'm working on it and is in a good point. I think in the next few days I release first version.

Answering your second question, there are generic modules for send packet, one is "Generic TCP-UDP", but I don't know if it's works in this case so you will have to try.

**Comment by LoganSulpizio** [comment]
That's great news!
Thanks to all the team for your great work, it is really appreciated!
