### ISSUE TITLE
Allen and Heath - DLive - Surface C3500 - Mix Rack CDM48

### ISSUE THREAD

**Issue by RockyRoadAudio** [bitfocus/companion-module-allenheath-dlive-ilive#8]
Hey there,

I had a DLive surface C3500 with a Mix Rack CDM48. 
I added the Instance Allen & Heath DLive. 
The connection said Ok for the IP address of the Mix Rack but would not work with the IP of the surface

The button command just wouldn't work so I'm wondering...

Are there specific DLive Mix Racks and surfaces that the companion only works with? 

Thx for the help.
Rocky

**Comment by MeestorX** [comment]
There's no TCP control of surfaces or the editor, only MixRacks.

**Comment by RockyRoadAudio** [comment]
Does that mean that the commands work but we don't see it reflected on the surface..?

**Comment by MeestorX** [comment]
Maybe. Been a while, but things like mutes and faders should be reflected on the surface. Did you try all the commands?
Pretty sure the IP in the module needs to be set to the IP of the MixRack.

**Comment by RockyRoadAudio** [comment]
Initially I set the IP to the Mix Rack. Companion showed a good connection, but when I programmed a simple mute channel command on the stream deck to test nothing showed on the console (surface). I didn't think of looking in the Director app to see if it was muting. I then tried the surface IP but companion couldn't connect to that so I put it back to the Mix Rack IP...

**Comment by MeestorX** [comment]
I guess keep playing with it until you figure it out. I haven't had any reports of problems.

**Comment by RockyRoadAudio** [comment]
Ok Thx,
I'll give an update once I figure it out. I've never had an issue with any other console with companion. Maybe it's a network issue... TBD
Rocky

**Comment by RockyRoadAudio** [comment]
Hey there, 
Testing a Dlive with a mac conected directly into a Mix Rack.
Companion shows connection as OK
The DLive firmware version is 1.88
However, I can't get any functions to work in companion with a dlive instance.
Don't know if the firmware version has anything to do with it...
Not sure what other parameters I can check in the console or computer...

**Comment by RockyRoadAudio** [comment]
Using Companion 2.2.0

**Comment by MeestorX** [comment]
Ok, just fired up my dLive to test.
Looks like somewhere along the way (probably 1.87) the firmware update changes the default MIDI channels.
On your console or in Director, go to Utility/Control and change the MIDI Channel from whatever it is to "1 to 5".
That fixed it for me.

**Comment by RockyRoadAudio** [comment]
Oh man! That worked...!
Thx!

**Comment by RockyRoadAudio** [comment]
A couple of command requests like in Midas and Yamaha if possible

1- Set channel send level to Mix (Aux)
2- Set channel mute to Mix (Aux)

Thanks for the help..
Rocky

**Comment by MeestorX** [comment]
Happy you got it working. I'll have to add that to the docs.

If you don't mind, post any further bugs, requests, etc. at my dedicated forum please.
